[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/home"
  to = "/"

[[redirects]]
  from = "/contact"
  to = "/feedback"

